-- 성별 정보 없는 행 제외
-- 1명이 여러 상품 구매 시 행 중복되기 때문에 DISTINCT 사용하여 COUNT

SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, COUNT(DISTINCT(UI.USER_ID)) USERS
FROM USER_INFO UI JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
