SELECT A.APNT_NO, 
       P.PT_NAME,
       P.PT_NO,
       D.MCDP_CD,
       D.DR_NAME,
       A.APNT_YMD
FROM DOCTOR D JOIN APPOINTMENT A 
ON D.DR_ID = A.MDDR_ID
JOIN PATIENT P 
ON A.PT_NO = P.PT_NO
WHERE D.MCDP_CD = 'CS' AND APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N'
ORDER BY 6;
