-- JOIN문 이용한 풀이
SELECT DISTINCT(C.CAR_ID) CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
WHERE CAR_TYPE = '세단' 
AND START_DATE LIKE '2022-10%'
ORDER BY C.CAR_ID DESC;

-- JOIN문 없는 풀이
SELECT DISTINCT(CAR_ID) CAR_ID
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE CAR_TYPE = '세단' AND START_DATE LIKE '2022-10%')
ORDER BY CAR_ID DESC;
