-- TYPE별 최대 길이 데이터만 추출
    -- MAX(LENGTH) & GROUP BY FISH_TYPE
    -- FROM 절 다중행 서브쿼리 활용 (IN)

SELECT A.ID, NI.FISH_NAME, A.LENGTH
FROM (
    SELECT ID, FISH_TYPE, LENGTH
    FROM FISH_INFO FI
    WHERE (FISH_TYPE, LENGTH) IN (
        SELECT FISH_TYPE, MAX(LENGTH)
        FROM FISH_INFO
        GROUP BY FISH_TYPE
)
) A
JOIN FISH_NAME_INFO NI ON A.FISH_TYPE = NI.FISH_TYPE;
