-- LEFT JOIN문 활용하여 O.DATETIME이 NULL값인 행들을 추출하는 방법
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I LEFT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.DATETIME IS NULL
ORDER BY I.DATETIME 
LIMIT 3


-- IN/OUT에 둘다 DATETIME이 있는 행들만 추출하여 제외하고 IN에 남은 행들을 추출하는 방법
SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN (SELECT I.ANIMAL_ID
                          FROM ANIMAL_INS I INNER JOIN ANIMAL_OUTS O
                          ON I.ANIMAL_ID = O.ANIMAL_ID)
ORDER BY DATETIME
LIMIT 3
