-- 1) IN 활용 MAX(FAVORITES) 서브쿼리로 구한 뒤 출력
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (SELECT FOOD_TYPE,MAX(FAVORITES)
                                 FROM REST_INFO
                                 GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC;


-- WITH 구문 & RANK() OVER로 순위 구한 뒤 출력
WITH FAV_RK AS (
                 SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
                 RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RK
                 FROM REST_INFO
                )
             
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM FAV_RK
WHERE RK = 1
ORDER BY FOOD_TYPE DESC
