-- 1) PARTITION BY + 서브쿼리를 사용한 풀이
SELECT SUB.YEAR, (SUB.MAX_SIZE - SUB.SIZE_OF_COLONY) AS YEAR_DEV, SUB.ID
FROM(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
    SIZE_OF_COLONY,
    MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) AS MAX_SIZE,
    ID
    FROM ECOLI_DATA
    ) SUB
ORDER BY 1, 2;

-- 2) 서브쿼리 없는 더 간단한 풀이
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
        (MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY) AS YEAR_DEV,
        ID
FROM ECOLI_DATA
ORDER BY 1, 2;
