-- ROOT 아이템 = C, D, E
-- 더이상 업그레이가 불가능한 아이템 = PARENT_ITEM_ID가 NULL인 값

SELECT I.ITEM_ID, I.ITEM_NAME, RARITY
FROM ITEM_INFO I LEFT JOIN ITEM_TREE T
ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC;
