-- 2022년 평가 점수 가장 높은 사원 
-- 평가 점수 = 상,하반기 점수 합

-- 1) LIMIT 활용하여 가장 높은 점수 사원 출력
SELECT SUM(G.SCORE) SCORE, 
       G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT D JOIN HR_EMPLOYEES E
ON D.DEPT_ID = E.DEPT_ID 
JOIN HR_GRADE G 
ON E.EMP_NO = G.EMP_NO
GROUP BY G.EMP_NO
ORDER BY SCORE DESC
LIMIT 1

2) RANK 활용하여 SCORE 1등 사원출력 (서브쿼리) 
SELECT SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT D JOIN HR_EMPLOYEES E
ON D.DEPT_ID = E.DEPT_ID 
JOIN (SELECT EMP_NO, SCORE, RANK() OVER (ORDER BY SCORE DESC) AS RANKING
      FROM(SELECT EMP_NO, SUM(SCORE) AS SCORE
      FROM HR_GRADE
      WHERE YEAR = '2022'
      GROUP BY EMP_NO) A 
      ) G
ON E.EMP_NO = G.EMP_NO
WHERE G.RANKING = 1
GROUP BY EMP_NO
